name = "blog"

workers_dev = true
route = ""
zone_id = ""
compatibility_date = "2023-10-30"

[build]
command = "npm run build"



[env.production]
node_compat = true

[build.environment]
NODE_VERSION = "18.18.0"