name = "blog"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"
publish = "out"

[build.processing]
skip_processing = false

[build.processing.html]
pretty_urls = true

[[redirects]]
from = "/*/*.txt"
to = "/:splat"
status = 301

